apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: POST

  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    user: fraud_admin
    secureJsonData:
      password: fraud_secret_2024
    jsonData:
      database: fraud_db
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    editable: false

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    url: http://clickhouse:8123
    jsonData:
      defaultDatabase: fraud_analytics
      username: fraud_admin
    secureJsonData:
      password: fraud_secret_2024
    editable: false
